def print_a():
    print("1", end="")
def print_b():
    print("2", end="")
def print_c():
    print("3", end="")
def print_d():
    print("4", end="")
def print_e():
    print("5", end="")
def print_f():
    print("6", end="")
def print_g():
    print("7", end="")
def print_h():
    print("8", end="")
def print_i():
    print("9", end="")
def print_g():
    print("0", end="")
print_h(), print_h(), print_g(), print_g(), print_e(), print_e(),print_e(), print_c(), print_e(), print_c(), print_e()